# Generated by Django 2.0 on 2017-12-18 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kkd2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_enrich',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='go_enrich',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
