# Generated by Django 2.0 on 2017-12-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkd2', '0002_auto_20171218_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='subgenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('Gene_stable_ID', models.CharField(max_length=20)),
                ('Transcript_stable_ID_version', models.CharField(max_length=20)),
                ('GO_term_accession', models.CharField(max_length=20)),
                ('GO_term_name', models.CharField(max_length=20)),
                ('NCBI_gene_ID', models.CharField(max_length=20)),
                ('Gene_name', models.CharField(max_length=20)),
                ('Gene_description', models.TextField()),
            ],
            options={
                'db_table': 'subgenes',
            },
        ),
    ]
