# Generated by Django 2.0 on 2017-12-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkd2', '0003_subgenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgenes',
            name='GeneID',
            field=models.CharField(default='nan', max_length=20),
            preserve_default=False,
        ),
    ]
