# Generated by Django 2.0 on 2017-12-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='go',
            table='mytable',
        ),
    ]
