# Generated by Django 2.0 on 2017-12-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkd', '0002_auto_20171217_1013'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='go',
            table=None,
        ),
    ]
