# Generated by Django 2.0 on 2017-12-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkd', '0003_auto_20171217_1015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='go',
            table='mytable',
        ),
    ]
