# Generated by Django 2.0 on 2017-12-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkd', '0004_auto_20171217_1027'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='go',
            table='go',
        ),
    ]
