# Generated by Django 2.0 on 2017-12-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkd', '0005_auto_20171217_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='go',
            old_name='Odd',
            new_name='Odds',
        ),
    ]
